[package]
name = "usbip-darwin"
version = "0.1.0"
edition = "2021"

[dependencies]
objc2 = { git = "ssh://git@github.com/carlossless/objc2.git", branch = "fix/objc2-io-usb-host"}
block2 = { git = "ssh://git@github.com/carlossless/objc2.git", branch = "fix/objc2-io-usb-host" }
dispatch2 = { git = "ssh://git@github.com/carlossless/objc2.git", branch = "fix/objc2-io-usb-host" }
objc2-foundation = { git = "ssh://git@github.com/carlossless/objc2.git", branch = "fix/objc2-io-usb-host" }
objc2-io-usb-host = { git = "ssh://git@github.com/carlossless/objc2.git", branch = "fix/objc2-io-usb-host" }
bytes = "1.10.1"
tokio = { version = "1", features = ["full"] }
bitflags = "2.9.1"
